### ISSUE TITLE
[BUG] gopro-telemetry function call is blocking every request on my express server

### ISSUE THREAD

**Issue by SolydBoy** [JuanIrache/gopro-telemetry#104]
**Describe the bug**
Gopro-telemetry function call is blocking every request on my express server

**To Reproduce**
Juste create a very basic express server like this one: 
```js
const express = require('express');
const bodyParser = require('body-parser');
const metadata2json = require('./export')

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

const port = process.env.PORT || 5000;

app.listen(port, () => {
        console.log(`App is listening on port ${port}.`);
    }
);

app.get("/helloworld", async (req, res) => {
    console.log("helloworld")
    res.send("helloworld")
})

app.get("/extract", async (req, res) => {
    await metadata2json('./GH020021.MP4', "TOTO.json")
    res.send("finish")
})
```

As you can see I have tow route, one that will serve as test ('/helloworld') and the other one that will extract my data.

Here is my metadata2json function:

```js
const goproTelemetry = require(`gopro-telemetry`);
const gpmfExtract = require('gpmf-extract');
const fs = require('fs');
process.env.FFPROBE_PATH = require('@ffprobe-installer/ffprobe').path;
const ffprobe = require('ffprobe-client');
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath(require('@ffmpeg-installer/ffmpeg').path);

const extractGPMF = async videoFile => {
    const ffData = await ffprobe(videoFile);

    for (let i = 0; i < ffData.streams.length; i++) {
        if (ffData.streams[i].codec_tag_string === 'gpmd') {
            return await extractGPMFAt(videoFile, i);
        }
    }
    return null;
};

const extractGPMFAt = async (videoFile, stream) => {
    let rawData = Buffer.alloc(0);
    await new Promise(resolve => {
        ffmpeg(videoFile)
            .outputOption('-y')
            .outputOptions('-codec copy')
            .outputOptions(`-map 0:${stream}`)
            .outputOption('-f rawvideo')
            .pipe()
            .on('data', chunk => {
                rawData = Buffer.concat([rawData, chunk]);
            }).on('end', resolve);
    });
    return rawData;
};

const metadata2json = async (file, dest) => {
    const gpmf = await extractGPMF(file);
    const element = {
        rawData: gpmf,
        timing: {
            frameDuration: 0,
            start: "",
            sample: []
        }
    };
    console.log(element);
    let telemetry = await goproTelemetry(element, {promisify: true});
    console.log("salut")
    fs.writeFile(dest, JSON.stringify(telemetry), err => {
        if (err) {
            return console.log(err);
        }
    });
    console.log('Telemetry saved as JSON');
    console.log(file);
};

module.exports = metadata2json;
```

When I run this and make a request on /extract and right after on /helloworld I have this output:
```

> test-express@1.0.0 start /home/basile_lamarque/tmp/test-express
> node index.js

App is listening on port 5000.
{
  rawData: <Buffer 44 45 56 43 00 01 1c b8 44 56 49 44 4c 04 00 01 00 00 00 01 44 56 4e 4d 63 0b 00 01 48 45 52 4f 38 20 42 6c 61 63 6b 00 53 54 52 4d 00 01 05 54 53 54 ... 5196778 more bytes>,
  timing: { frameDuration: 0, start: '', sample: [] }
}
salut
Telemetry saved as JSON
./GH020021.MP4
helloworld

```

**Expected behaviour**
I no clue of what happen, maybe ```goproTelemetry``` is consuming all my thread, I don't know.

**Additional context**
I have try to add this but it gave me the same result
```js
let telemetry = await goproTelemetry(element, {promisify: true});
```

**Comment by JuanIrache** [comment]
Hi @SolydBoy 

I'm not sure why that would be happening, but will do some research. In the meantime, could you rule out that it is not the `extractGPMF `function what's causing trouble? Maybe save its output to a file and run `metadata2json` with the saved output.

That's what comes to my mind now. Will let you know if I make any progress.

**Comment by SolydBoy** [comment]
Hi @JuanIrache 

I don't think ```extractGPMF``` is causing any trouble because the debug log immediately after the function is displayed almost instantly.

```js
const metadata2json = async (file, dest) => {
    const gpmf = await extractGPMF(file);
    const element = {
        rawData: gpmf,
        timing: {
            frameDuration: 0,
            start: "",
            sample: []
        }
    };
    console.log("After extract GPMF"); // this one
    let telemetry = await goproTelemetry(element, {promisify: true});
    console.log('After goproTelemetry');
    fs.writeFile(dest, JSON.stringify(telemetry), err => {
        if (err) {
            return console.log(err);
        }
    });
    console.log('Telemetry saved as JSON');
    console.log(file);
};
```

output

```
> test-express@1.0.0 start /home/basile_lamarque/tmp/test-express
> node index.js

App is listening on port 5000.
After extract GPMF // stay stuck here for a while
After goproTelemetry
Telemetry saved as JSON
./GH020021.MP4
```

I think I don't understand what you suggested but I try to save ```extractGPMF``` to a .json but it didn't change anything. :(

My try
```js
const extractGPMF2json = async (file, dest) => {
    const gpmf = await extractGPMF(file);
    const element = {
        rawData: gpmf,
        timing: {
            frameDuration: 0,
            start: "",
            sample: []
        }
    };
    await fs.writeFileSync(dest, JSON.stringify(element));
    console.log('GPMF save to: ' + dest);
}

const debugmetadata2json = async (file, dest) => {
    await extractGPMF2json(file, "./GPMF.json");
    const contents = fs.readFileSync("./GPMF.json")
    const element = await JSON.parse(contents)
    element.rawData = Buffer.from(element.rawData.data);
    let telemetry = await goproTelemetry(element)
}
```

Thank you for helping me!

**Comment by JuanIrache** [comment]
Thanks for trying that. I will experiment with this as soon as I can. It might take me a while, as I am busy with something urgent. So if someone else is able to make any progress, go ahead and much appreciated

**Comment by JuanIrache** [comment]
Ok, after some tests I believe this is normal. I created this repo for testing: https://github.com/JuanIrache/gtasynctest

You can run app.js, which will accept requests to /process, /process-with-timeout and /ping

You can use the pinger.js script to test the server availability every 500ms (or change it to whatever you want)

And the consecutive.js script will make consecutive requests.

The thing, I believe, is that even if the code is run asynchronously in a correct manner, it does not run in parallel (in a separate thread) and it takes time. It will therefore be blocking. Async or promises just offset the execution time, and you can offset it more with setTimeout (see process-with-timeout), but whenever it runs, it will block the thread. For it to be non-blocking, you would have to run the code in a separate thread: https://nodejs.org/api/worker_threads.html

**Comment by SolydBoy** [comment]
Okay i will try that !
Thank you for you reply

**Comment by JuanIrache** [comment]
Should be fixed on 95823a2ae72bb047c20711a94cdbbf2f50251574

There are significant changes, but if you were already using this as a promise, they won't affect you. You don't need to specify the promisify option any more, it's a promise by default. Internally, many functions have been turned into promises (or async functions), so basically this creates a myriad of opportunities for the server to do other things before the code completes.

**Comment by JuanIrache** [comment]
Nevermind, this is still blocking, I'm working on a better solution

**Comment by JuanIrache** [comment]
Fixed in https://github.com/JuanIrache/gopro-telemetry/commit/f33787d5ad9b935138b043abaf5494cbfe826f68

Ok, now I've set multiple points where, in addition to using async functions, the code forces them to leave time for other processes by using setImmediate. It's not the best option (separate threads would probably be best), but I think it's what I can do at the moment without breaking compatibilities

**Comment by sarfata** [comment]
> The thing, I believe, is that even if the code is run asynchronously in a correct manner, it does not run in parallel (in a separate thread) and it takes time. It will therefore be blocking. Async or promises just offset the execution time, and you can offset it more with setTimeout (see process-with-timeout), but whenever it runs, it will block the thread. For it to be non-blocking, you would have to run the code in a separate thread: https://nodejs.org/api/worker_threads.html

I think you were spot on in that comment. Running the code in a worker (browser or node) is the correct solution. Making it asynchronous just slows things down and makes the code more complicated. There is no going around the fact that it does a hard computation on a large volume of data and that is going to take a while.

You said in the comments that it's a difficult tradeoff, have you measured the impact of the `setImmediate` calls on performance?

**Comment by JuanIrache** [comment]
I have not made precise measurements. I did spend some time testing different frequencies of `setImmediate` calls (basically, how deep inside loops I was calling it, or how often) and settled on what seemed a reasonable balance between non-blocking and performace. This is by no means a perfect solution, but I don't know when I will have time to implement a worker solution.

**Comment by sarfata** [comment]
I did some test this morning between the async version with `setImmediate` calls and another version with all the async stuff removed. I did not see any significant difference so I think the pragmatic thing to do is to leave it as it is now if it helps some people... The only downside is that the code is a bit more complicated to read.
