### ISSUE TITLE
Hero7 Silver missing streams?

### ISSUE THREAD

**Issue by Niproblema** [JuanIrache/gopro-telemetry#129]
Debug export: from gopro-telemetry:
device name:"HERO7 Silver"
   ACCL:Object {samples: Array(278796), name: "Accelerometer (z,x,y)", units: "m/s2"}
   GPS5:Object {samples: Array(25387), name: "GPS (Lat., Long., Alt., 2D speed, 3D speed)", units: Array(5)}
   GYRO:Object {samples: Array(139344), name: "Gyroscope (z,x,y)", units: "rad/s"}
   ISOE:Object {samples: Array(83943), name: "Sensor ISO"}
   SHUT:Object {samples: Array(83943), name: "Exposure time (shutter speed)", units: "s"}
   WBAL:Object {samples: Array(83943), name: "White Balance temperature (Kelvin)"}
   WRGB:Object {samples: Array(83943), name: "White Balance RGB gains"}

Meanwhile Dashware csv export discovers other also like 
TSMP,
TMPC,
SIUN,
MTRX
ORIN,
GPSF,
GPSU,
GPSP,
+ few more

Am I doing something wrong?
Also how do you export it to CSV with some template?

**Comment by JuanIrache** [comment]
Those keys are nested inside the main ones. They are used for interpreting the data of each stream. You can get a JSON output closer to the raw data, including those keys, with the raw option. You can format the output as csv with the preset option, but it will not follow any template. If you want a custom format you will have to encode it, maybe from the standard JS object output

**Comment by Niproblema** [comment]
Thank you for quick response. You are right, took me a bit to learn how to use your lib. Eventually I got it working. Thanks for providing this cool lib.

**Comment by JuanIrache** [comment]
Thanks to you!
