### ISSUE TITLE
Missing dependency in npm installer

### ISSUE THREAD

**Issue by Mark-Downer** [JuanIrache/gopro-telemetry#142]
When using command "npm i gopro-telemetry" it is failing because it cannot find the file ssh://git@github.com/jleppert/egm96.git

Please update the installer so that it either has that dependency in the git repository or edit the installer so it's not trying to find it.

**Comment by JuanIrache** [comment]
Hello @Mark-Downer ,

I cannot reproduce your issue. The module and dependencies install fine on my systems. Could it be that npm needs some setting enabled for it to install modules directly from GitHub?

**Comment by Mark-Downer** [comment]
That's annoying. I've tried on three different machines including one completely clean version of Windows 10 in a virtual environment all with new clean installs of npm and they all had this issue. 

![Capture](https://user-images.githubusercontent.com/65881393/91916661-ca26f880-ed11-11ea-8e1e-609623fd6e75.PNG)

**Comment by JuanIrache** [comment]
Does deleting package-lock.json help?

**Comment by Mark-Downer** [comment]
@JuanIrache 
> Does deleting package-lock.json help?

No, I deleted it from two different locations and it still errored. I can confirm that the machine I tested this on has got git installed so that's not the problem.

Thanks
