### ISSUE TITLE
Telemetry Extractor Lite VIRB time bug

### ISSUE THREAD

**Issue by SirJohnDoe** [JuanIrache/gopro-telemetry#163]
I've been using the Telemetry Lite tool for a while now, to export GPX files suitable for VIRB. It works pretty well, but today I discovered a bug when processing some video files (using time gauges): a recording of 35 minutes or so has been split in 4 parts of 4/4/4/1 GB. I've exported VIRB gpx files for all of them and processed them in VIRB. I noticed, however, that they all start and end with the same time, instead of the time being sequential. See the pictures below for a comparison between the GPX and VIRB export, the former being correct:

![image](https://user-images.githubusercontent.com/11654657/110966518-9fb79700-8355-11eb-8ca8-4db9daa47d79.png)

![image](https://user-images.githubusercontent.com/11654657/110966357-76970680-8355-11eb-98f4-2ef9f81f0a5e.png)

**Comment by SirJohnDoe** [comment]
Solved by changing Base Time from 'Auto' to 'GPS'.

**Comment by JuanIrache** [comment]
Hi @SirJohnDoe , Virb exports use MP4 times by default (auto), which can have the result you are seeing. This decision was made because with some rouce files the MP4 times seemed more reliable for Virb Edit work, but if you want to avoid the problem with dates you can choose GPS times manually
