### ISSUE TITLE
Wrong Axis Order

### ISSUE THREAD

**Issue by xshuai1996** [JuanIrache/gopro-telemetry#165]
Hi,

I didn't read your code but tested your online tool https://goprotelemetryextractor.com/free/# with my GoPro7. I found that in the output data, the axis order is not inconsistent with official document https://github.com/gopro/gpmf-parser, which suggests for Hero 5 the axis order of ACCL and GYRO is Z/X/Y, but starting from hero 6 it has been changed to Y/-X/Z. The result outputted by your tool used Z/X/Y without considering the camera model.

**Comment by JuanIrache** [comment]
Hi @xshuai1996 

I think this is expected.
The data contains instructions to transform the axes (ORIN, ORIO, MTRX) just like it contains scaling instructions (SCAL). Once these transformations are applied axes of all cameras should be equivalent.

You can get the original data order by using the raw option (not really raw, to be clear, just with minimal processing and some data that helps further interpretation)

**Comment by xshuai1996** [comment]
Cool! Actually I wrote a py script to parse the MET track (i.e. binary telemetry data, I guess this is the raw you mentioned) just now and didn't handle the ORIN, ORIO, MTRX because there's no explanation for these 3 segments in official documents. I will look into it. Thank you so much for your reply and help :)

**Comment by JuanIrache** [comment]
Cool. I'm not sure where I got that info from. Maybe from a discussion in the issues section
