### ISSUE TITLE
Using gopro-telemetry in web browser

### ISSUE THREAD

**Issue by jackybourgeois** [JuanIrache/gopro-telemetry#173]
Hello,

First of all, thanks a lot for this repository! I have been using it in NodeJS for a while and I now want to use it as part of an Angular app.

I run into the issue that setImmediate() is receiving very little support and most web browsers do not implement it. Editing the breathe.js file to skip this function makes it work in the web browser. But I wonder if you encountered this challenge before, maybe I'm not using the library properly?

I also understand that skipping this function certainly freezes (part of) the web app while processing the file, but that already sounds like optimisation for what I do!

**Comment by JuanIrache** [comment]
Hi Jack,

Glad the repo is proving useful. I have not used this on the browser directly but I know other users have. I suppose they are bundling and polifilling the library (and things like that) to make it compatible with most browsers.

**Comment by jackybourgeois** [comment]
Thanks Juan, I found this [setImmediate](https://github.com/yuzujs/setImmediate) npm module by [YuzuJS](https://github.com/YuzuJS) which solve the issue.

**Comment by pavlosharhan2** [comment]
> Thanks Juan, I found this [setImmediate](https://github.com/yuzujs/setImmediate) npm module by [YuzuJS](https://github.com/YuzuJS) which solve the issue.

Hi @jackybourgeois 
Could you please explain a little bit, how did you use setImmediate in order to be able to run gopro-telemetry in the broser?
I'm trying to achieve the same thing

**Comment by jackybourgeois** [comment]
Hi @pavlosharhan2, it's been a while! We ended up making the go-pro telemetry extraction on the server side. The solution in the browser was not reliable at that time.
