### ISSUE TITLE
[DOUBT] GO PRO Files missing track data after renaming

### ISSUE THREAD

**Issue by aeciolevy** [JuanIrache/gopro-telemetry#180]
I have some GO PRO files that I just copied to the computer and renamed, and when I use [gpmf-extract](https://www.npmjs.com/package/gpmf-extract) it says track not found. Is this actually a thing, rename could change anything in the metadata of the file. Or maybe just copying from the SD Card to the computer could anything be changed?

**Comment by JuanIrache** [comment]
Neither renaming a file or copying it from the SD card via standard means can dp anything to the metadata track, as far as I can tell. Did you maybe use some photo/video importing tool that reencodes the video to a new file, instead of the standard system copying process?

**Comment by aeciolevy** [comment]
> Neither renaming a file or copying it from the SD card via standard means can dp anything to the metadata track, as far as I can tell. Did you maybe use some photo/video importing tool that reencodes the video to a new file, instead of the standard system copying process?

I have not done anything other than rename. I have done some tests, and there are other videos in different moments of the days and the telemetry is all right, so maybe the GPS signal or something went wrong.

I was able to extract the info from other videos.

I bought the Telemetry Overlay by the way (great product).  I would like to represent the speed on a 2D-axis graph is that possible? I know this is not the right forum to discuss that, but if there is a way to do or I could contribute to that I would be down for that. Thanks

**Comment by JuanIrache** [comment]
See the "Speed vs Time" gauge. You can also create a Custom Scope one and choose the Speed data (nested inside the GPS group)
