### ISSUE TITLE
KML & GPX presets- invalid characters

### ISSUE THREAD

**Issue by barney2074** [JuanIrache/gopro-telemetry#181]
Hello,

Firstly- thank you for gopro-telemetry- I'm only getting started, but it seems very useful

When using the gpx & kml presets, the output contains invalid characters- for example in the KML file, `\n` and `\` characters
![image](https://user-images.githubusercontent.com/25944617/199144571-321ac2d4-4d3c-4cdb-b56f-f31cbe5ea1da.png)

I can fix this by post-processing the output files, but how can I prevent this from occurring ?

thanks

Andrew

**Comment by JuanIrache** [comment]
Hi. I'm glad you find the module useful.

`\n` are line breaks. I don't think they should be considered invalid, even if the typical line breaks are not the same on all operating systems. If you think this is wrong, can you provide more context?

Thank you

**Comment by barney2074** [comment]
Hi @JuanIrache 

Yes, I realise they are line breaks (and fairly easy to clean up)- but applications such as Google Earth or QGIS will not open the KML or GPX files- with errors of incorrect format/syntax

thanks

Andrew

**Comment by JuanIrache** [comment]
Are line breaks incorrect in GPX files?

**Comment by barney2074** [comment]
Hi @JuanIrache 

I've played around with it some more, and tested the other presets.
It seems that the presets other than geojson and mgjson give me literal newline (\n) and backslash characters in the outputs
i.e geojson and mgjson are ok

I was originally running on a Ubuntu machine, but I've also tested on a Windows machine & it behaves the same

I've had a look at the code & would guess that something like this part of toCsv.js might have something to do with it ?
![image](https://user-images.githubusercontent.com/25944617/199361442-30ef1403-a2fa-4ddb-b2ac-396edb3ccd6e.png)


Andrew

**Comment by JuanIrache** [comment]
That is indeed where new lines are created. What I don't see is why a GPX
file should not have new lines. Could you provide context for that?

**Comment by barney2074** [comment]
Hi @JuanIrache 

I'm not sure if I'm missing something- but the problem (for me at least) is that the output contains literal `\n` characters (not new lines)

So for instance- a CSV file looks like this
![image](https://user-images.githubusercontent.com/25944617/199428104-f95e01a0-54f0-4cba-803a-aa96b72f6fe3.png)

thanks for your help- I can easily fix this after the files have been generated

Andrew

**Comment by barney2074** [comment]
Thanks Juan
Let me know if there is anything I can help with to replicate or solve the issue

(I don't have any JS skills to speak of)

Andrew

**Comment by forna** [comment]
I have the exact same issue.
AFAIK the newline character is '\r\n', not just '\n'.
See: https://stackoverflow.com/questions/4321041/javascript-newline-character

**Comment by forna** [comment]
In addition to the \n you also have the escape quotes \\"
It means you are using JSON.stringify to save the GPX data.
However the GPX is in XML, not JSON, so it is incorrect to use the JSON.stringify.

While for telemetry it looks like this (notice the fs.writeFileSync with JSON.stringify):
```
gpmfExtract(file)
    .then(extracted => {
        goproTelemetry(extracted, {}, telemetry => {
            fs.writeFileSync('full-telemetry.json', JSON.stringify(telemetry));
            console.log('Telemetry saved as JSON');
        });
    })
    .catch(error => console.error(error));
```

For the GPX it looks like this (no JSON.stringify):
```
gpmfExtract(file)
    .then(extracted => {
        goProTelemetry(extracted, {
            preset: 'gpx'
        }, telemetry => {
            fs.writeFileSync( 'gps-only.gpx', telemetry);
            console.log('GPS saved as GPX');
        });
    })
    .catch(error => console.error(error));

```
