### ISSUE TITLE
groupTimes option seems to be broken

### ISSUE THREAD

**Issue by haimat** [JuanIrache/gopro-telemetry#182]
I have a GoPro video (from a HERO10 Black) with a duration of about 8:30 min:

```
$ ffprobe GX050150.mp4
...
Duration: 00:08:39.22, start: 0.000000, bitrate: 45017 kb/s
...
```

When I run `gopro-telemetry` (as suggested via `gpmf-extract`) with option `groupTimes = "frames"`, then output seems correct - I get a result for every ~33 ms (as I can see in the JSON result `cts` values). However, if I want to use another grouping time, this does not work anymore. For example with `groupTimes = 10` I get only four result samples with these `cts` values:
* "cts": 0
* "cts": 528.3055555555554
* "cts": 51032.30840715651
* "cts": 310120.20807889925

Is this a bug in `gopro-telemetry`, or am I using this option wrong?

**Comment by JuanIrache** [comment]
Hi Matthias, That is unexpected indeed. Can you provide a minimal project
that shows this problem? I have been using groupTimes for years without
noticing this.

To clarify, passing 10 would mean you want one sample every 10
milliseconds. If you are using this with the GPS stream, there normally are
samples every 55 or 100 milliseconds, so many of the samples you get will
be interpolated between existing values. That does not explain the result
you are getting, though. What other options are you passing?

Thank you.

**Comment by haimat** [comment]
The code I am using to extract is this:

```
const goproTelemetry = require('gopro-telemetry');
const gpmfExtract = require('gpmf-extract');
const { exit } = require('process');
const path = require('path');
const fs = require('fs');

function bufferAppender(path, chunkSize) {
    return function (mp4boxFile) {
        var stream = fs.createReadStream(path, { 'highWaterMark': chunkSize });
        var bytesRead = 0;
        stream.on('end', () => {
            mp4boxFile.flush();
        });
        stream.on('data', (chunk) => {
            var arrayBuffer = new Uint8Array(chunk).buffer;
            arrayBuffer.fileStart = bytesRead;
            var next = mp4boxFile.appendBuffer(arrayBuffer);
            bytesRead += chunk.length;
        });
        stream.resume();
    }
}

var videoIn = myArgs[0];
var jsonOut = myArgs[1];
var grouping = myArgs[2];  // "frames" or a value in milliseconds

console.log("Reading video data:", videoIn);
gpmfExtract(bufferAppender(videoIn, 10 * 1024 * 1024)).then(res => {
    console.log("Parsing GPS telemetry data ...");
    options = { stream: ["GPS5"], groupTimes: grouping, smooth: 3, repeatHeaders: true, repeatSticky: true };
    goproTelemetry(res, options, telemetry => {
        fs.writeFileSync(jsonOut, JSON.stringify(telemetry, null, 2));
        console.log("GoPro telemetry data saved:", jsonOut);
        exit(0);
    });
});
```

This script I then call with `node telemetry.js video.mp4 gps.json 10`.
Using 10 as value was just an example. I also get invalid results with any other value here - it only works with "frames".

**Comment by JuanIrache** [comment]
At a first glance, I would say you are passing a string to groupTimes. Try var
grouping = +myArgs[2]; to get the argument as a number.

Does that help?

**Comment by haimat** [comment]
Aweseome, that's it, thanks.
Converting the string value to a number was the missing part.
