### ISSUE TITLE
`setImmediate` is not supported in any browser

### ISSUE THREAD

**Issue by Akxe** [JuanIrache/gopro-telemetry#190]
You are using `setImmediate` in [breathe.js](https://github.com/JuanIrache/gopro-telemetry/blob/master/code/utils/breathe.js), but it is not a browser-supported API at the moment. Would you mind switching the API to use `setImmediate || setTimeout`?

**Comment by JuanIrache** [comment]
Sounds good. The library was conceived to be compiled, but a PR in this direction is welcome

**Comment by JuanIrache** [comment]
With 74eb04a9de99d86c881c3635e55dd9a1357b1fc7 merged, we should close this one too, right?
