### ISSUE TITLE
Remove egm96

### ISSUE THREAD

**Issue by Akxe** [JuanIrache/gopro-telemetry#192]
When testing, I noticed that when bundled, the egm96 library is 2.5mb in size. There must be a better way to convert to the correct output without being the 99% of the library size...

**Comment by JuanIrache** [comment]
I see the following options:

- We move it to a separate dependency. Downside: It weighs the same after npm installing gopro-telemetry
- We rely on some API for altitude corrections. Downside: We lose offline functionality, and have to rely on third parties
- We let the user optionally provide an egm96 data file if they want altitude corrections (might be the simplest option)
- A combination of the above
- We disable altitude corrections altogether (I would rule this out)

**Comment by Akxe** [comment]
I like to option that user might provide the library on its own.

I see two options:
* We declare `egm96-universal` as an optional peer dependency; we could then use it only when the user installs it on his own.
* We declare a new option, `seaLevelCorrection`,  that would do the same thing as now...

I do, however see a problem if the user is not aware of the option to provide seaLeveCorrection fn/library he would not know how to fix it... A warning could do it, but I am not sure that that would be a good fix either.

**Comment by JuanIrache** [comment]
I like the optional peer dependency route. Then in `processGPS5.js` we only proceed to the condition around line 45 if the library is present. Maybe print a warning if `egm96-universal` is missing. The warning can be avoided by setting the `ellipsoid` option to `true` and `geoidHeight` to `false`

**Comment by Akxe** [comment]
Just as I finish types for the library I will look into making the dependency optional and let you do the warning :)
