### ISSUE TITLE
Speed field isn't present in GPX 1.1

### ISSUE THREAD

**Issue by mahmad8** [JuanIrache/gopro-telemetry#38]
https://github.com/JuanIrache/gopro-telemetry/blob/7e4c1af67d3ebad05149b408b19399e26a548dd9/code/toGpx.js#L68

Not sure but I get a validation error when I use this. There's no "speed" field in GPX 1.1. See https://www.topografix.com/GPX/1/1/gpx.xsd.

**Comment by JuanIrache** [comment]
I think this comes from the previous 1.0 GPX specification https://www.topografix.com/gpx_manual.asp

I put it there because it was read properly by some software, for example Virb Edit (I seem to remember).

Would you specify the speed in some other way? Whay do you suggest?
