### ISSUE TITLE
desc should appear before src

### ISSUE THREAD

**Issue by mahmad8** [JuanIrache/gopro-telemetry#39]
https://github.com/JuanIrache/gopro-telemetry/blob/7e4c1af67d3ebad05149b408b19399e26a548dd9/code/toGpx.js#L100

See https://www.topografix.com/GPX/1/1/gpx.xsd. There's a comment saying that elements must appear in order.

**Comment by JuanIrache** [comment]
Can you submit a pull request with the fix?
