### ISSUE TITLE
[Website] GPS precision change yelds incoherent GPS points

### ISSUE THREAD

**Issue by adrien-jacquot** [JuanIrache/gopro-telemetry#60]
Hello,

I recently tried [your website](https://tailorandwayne.com/gopro-telemetry-extractor/) to extract GPS coordinates from a Hero 7 Black camera.
I tried changing the precision parameter and visualized the resulting coordinates in Google Maps.
As you can see in the screenshot below, the results are quite weird.
The 3 colors indicates 3 precision values:

- Red is 10k
- Green is 625
- Blue is 529

I would have guessed that the 3 data points would be overlapping, with some points filtered out for green and blue.
Any idea what is going wrong?

PS: Haven't tried using the code yet, just the website

![image](https://user-images.githubusercontent.com/45296023/64631679-de366380-d3f7-11e9-8e76-7a76b3d8e389.png)

**Comment by JuanIrache** [comment]
Yes, that's not the output I would expect. It will be a few days until I can debug this, but could you share the video (or LRV) file privately with me? Otherwise if you find out what causes this feel free to PR to the Dev branch.

Thanks

**Comment by JuanIrache** [comment]
Sorry, I can't reproduce the problem
