### ISSUE TITLE
RangeError [ERR_FS_FILE_TOO_LARGE]

### ISSUE THREAD

**Issue by theomessin** [JuanIrache/gopro-telemetry#63]
Trying to get the GoPro telemetry data for a 4GB video using the sample code:
```node
const gpmfExtract = require('gpmf-extract');
const goproTelemetry = require(`gopro-telemetry`);
const fs = require('fs');

const file = fs.readFileSync('path_to_your_file.mp4');

gpmfExtract(file)
  .then(extracted => {
    let telemetry = goproTelemetry(extracted);
    fs.writeFileSync('output_path.json', JSON.stringify(telemetry));
    console.log('Telemetry saved as JSON');
  })
  .catch(error => console.log(error));
```
Getting `RangeError [ERR_FS_FILE_TOO_LARGE]: File size (4001043636) is greater than possible Buffer: 2147483647 bytes`. Is there a way to extract the gpmf data without sync. reading the entire file?

**Comment by theomessin** [comment]
I guess one solution (not really pretty though) is to manually extract the `gpmd` stream from the input video using ffmpeg: `ffmpeg -i video.mp4 -map 0:3 -c copy telemetry.mp4`

**Comment by JuanIrache** [comment]
Yes, that's a known issue caused mostly by Node's size limitations. And your solution is also what I do when working on Node. You can automate the extraction with child_process.exec and similar stuff, and it's actually a much faster extraction than with gmpf-extract, but of course you don't get the timing data automatically.

I have not had time to work on a proper all-javascript solution, so I'll leave this open in case someone wants to jump in an provide it.

**Comment by theomessin** [comment]
> you don't get the timing data automatically.
What exactly do you mean by this?

**Comment by JuanIrache** [comment]
gopro-telemetry expects timing information about the video file (starting time, frame rate...). gpmf-extract provides that alongside the binary data. If you extract the binary data with ffmpeg, you will have to calculate the timing information too, if you want to take advantage of all of gopro-telemetry's capabilities

**Comment by theomessin** [comment]
Oh, didn't know that. Do you have any code showing how that could be done?

**Comment by JuanIrache** [comment]
Not that I can share at the moment, but it goes along the lines of using ffprobe to show frames, select streams, read intervals... and reproduce the structure that gpmf-extract provides:

```
{ frameDuration: 0.03336666666666667,
  start: 2017-04-17T19:27:57.000Z,//Date object
  samples:
   [ { cts: 0, duration: 1001 },//Starting point and duration in milliseconds
     { cts: 1001, duration: 1001 },
     { cts: 2002, duration: 1001 },
     { cts: 3003, duration: 1001 },
     { cts: 4004, duration: 1001 } ] }
```

Ffmpeg has plenty of documentation, buit it's kind of all over the place

**Comment by plouj** [comment]
Whoever is going with the approach of using `ffmpeg` to extract the `gpmd` steam can also downsample the video to make it fit into the 2GB size limitation in one go as a quick and dirty solution.

The following reduces HERO5 4k 60fps 60mbit video from 3.4GB down to 22MB:
```
ffmpeg.exe -i GOPR0001.MP4 -vf scale=320:-1 -map 0:0 -map 0:1 -map 0:3 -codec:v mpeg2video -codec:d copy -codec:a copy -y GOPR0001-small.MP4
```

and allows using `gpmfExtract` to extract both the telemetry (stream `0:3` in the above case) and the timing data in one go.

**Comment by JuanIrache** [comment]
@plouj that's a pretty interesting approach. I hadn't thought of combining both ffmpeg and gpmf-extract. Ideally there should be an all JS/Nodejs solution, though

**Comment by MauriceMorrey** [comment]
Any breakthrough with this at all?

**Comment by JuanIrache** [comment]
Hi @MauriceMorrey . No, the above solutions are still recommended

**Comment by himynamesdave** [comment]
[We take a similar approach to get around this](https://www.trekview.org/blog/2022/gopro-telemetry-exporter-getting-started/):

There is an easy way around this to obtain the telemetry file; make a copy of the input video, stripping out its video and audio streams but keeping the telemetry stream to reduce the filesize. This can be done using ffmpeg like so:

```shell
ffmpeg -i INPUT.mp4 -map 0:2 OUTPUT-telemetry-only.MP4
```

This will reduce a 4GB video to a video of 30MB containing only telemetry.

**Comment by MauriceMorrey** [comment]
Thanks for this @himynamesdave. Big game changer. I'm a big fan of trek view!

**Comment by ajsnyde** [comment]
Getting `Track not found` when using these solutions for files from my GoPro Hero 11. Ran ffprobe and got the results below:
```~/orbslam3_docker/inputFiles/raw/R (main *)$ ll
total 14190844
drwxrwxrwx 2 smbuser smbgroup        4096 Mar  5 10:53 ./
drwxrwxrwx 4 smbuser smbgroup        4096 Feb 27 16:01 ../
-rwxrwxrwx 1 dread   dread    11160496685 Feb 20 20:41 BoneCircuit1.MP4*
-rw-rw-r-- 1 dread   dread      103174000 Mar  5 10:52 EyeToBoneJump.mp4
-rw-rw-r-- 1 dread   dread     3120108315 Feb 27 20:05 EyeToBoneJump.MP4
-rwxrwxrwx 1 smbuser smbgroup   143519489 Feb 19 14:01 GX010030.MP4*
-rw-rw-r-- 1 dread   dread        4096700 Mar  5 10:53 OUTPUT-telemetry-only.mp4
~/orbslam3_docker/inputFiles/raw/R (main *)$ ffprobe EyeToBoneJump.MP4 
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'EyeToBoneJump.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf58.76.100
  Duration: 00:04:12.01, start: 0.000000, bitrate: 99046 kb/s
  Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 2704x2028 [SAR 1:1 DAR 4:3], 98848 kb/s, 119.88 fps, 119.88 tbr, 120k tbn, 119.88 tbc (default)
    Metadata:
      handler_name    : GoPro H.265
      vendor_id       : [0][0][0][0]
      timecode        : 20:24:49:37
  Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
    Metadata:
      handler_name    : GoPro AAC  
      vendor_id       : [0][0][0][0]
  Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
    Metadata:
      handler_name    : GoPro H.265
      timecode        : 20:24:49:37
Unsupported codec with id 0 for input stream 2
~/orbslam3_docker/inputFiles/raw/R (main *)$ 
```

**Comment by JuanIrache** [comment]
> Getting `Track not found` when using these solutions for files from my GoPro Hero 11. Ran ffprobe and got the results below:
> 
> ```
> ~/orbslam3_docker/inputFiles/raw/R (main *)$ ll
> total 14190844
> drwxrwxrwx 2 smbuser smbgroup        4096 Mar  5 10:53 ./
> drwxrwxrwx 4 smbuser smbgroup        4096 Feb 27 16:01 ../
> -rwxrwxrwx 1 dread   dread    11160496685 Feb 20 20:41 BoneCircuit1.MP4*
> -rw-rw-r-- 1 dread   dread      103174000 Mar  5 10:52 EyeToBoneJump.mp4
> -rw-rw-r-- 1 dread   dread     3120108315 Feb 27 20:05 EyeToBoneJump.MP4
> -rwxrwxrwx 1 smbuser smbgroup   143519489 Feb 19 14:01 GX010030.MP4*
> -rw-rw-r-- 1 dread   dread        4096700 Mar  5 10:53 OUTPUT-telemetry-only.mp4
> ~/orbslam3_docker/inputFiles/raw/R (main *)$ ffprobe EyeToBoneJump.MP4 
> ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
>   built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
>   configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
>   WARNING: library configuration mismatch
>   avcodec     configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared --enable-version3 --disable-doc --disable-programs --enable-libaribb24 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libtesseract --enable-libvo_amrwbenc --enable-libsmbclient
>   libavutil      56. 70.100 / 56. 70.100
>   libavcodec     58.134.100 / 58.134.100
>   libavformat    58. 76.100 / 58. 76.100
>   libavdevice    58. 13.100 / 58. 13.100
>   libavfilter     7.110.100 /  7.110.100
>   libswscale      5.  9.100 /  5.  9.100
>   libswresample   3.  9.100 /  3.  9.100
>   libpostproc    55.  9.100 / 55.  9.100
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'EyeToBoneJump.MP4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2mp41
>     encoder         : Lavf58.76.100
>   Duration: 00:04:12.01, start: 0.000000, bitrate: 99046 kb/s
>   Stream #0:0(eng): Video: hevc (Main) (hvc1 / 0x31637668), yuvj420p(pc, bt709), 2704x2028 [SAR 1:1 DAR 4:3], 98848 kb/s, 119.88 fps, 119.88 tbr, 120k tbn, 119.88 tbc (default)
>     Metadata:
>       handler_name    : GoPro H.265
>       vendor_id       : [0][0][0][0]
>       timecode        : 20:24:49:37
>   Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
>     Metadata:
>       handler_name    : GoPro AAC  
>       vendor_id       : [0][0][0][0]
>   Stream #0:2(eng): Data: none (tmcd / 0x64636D74)
>     Metadata:
>       handler_name    : GoPro H.265
>       timecode        : 20:24:49:37
> Unsupported codec with id 0 for input stream 2
> ~/orbslam3_docker/inputFiles/raw/R (main *)$ 
> ```
> 
> And when running the latest telemetry extractor: ![image](https://user-images.githubusercontent.com/11302823/222971573-a688393f-5eee-4aef-b8c8-532ea8591b28.png)

your file does not seem to have the gpmd track. Is that an original GoPro file or did it go through some kind of processing?

**Comment by ajsnyde** [comment]
Good eye, that's what's missing. Among other things, I was trying to crop a video length and preferably lower the resolution and forgot about preserving the gpmd track. After a couple minutes of fiddling I got this:
`ffmpeg -ss 00:00:00 -to 00:04:12 -i BoneCircuit1.MP4 -vf scale=960:-1 -map 0:3 EyeToBoneJump2.mp4`
Thanks!
