### ISSUE TITLE
Add JSDoc/.d.ts type hints

### ISSUE THREAD

**Issue by Akxe** [JuanIrache/gopro-telemetry#81]
As the title says. It would come handy to have types with explanation in code rather than in the readme.

**Comment by JuanIrache** [comment]
Hi @Akxe , I have no experience with typescript. Would you be albe to suggest the code changes?

Thanks

**Comment by Akxe** [comment]
Are you interested to convert the codebase to TS? If not we can generate a file with external types for the library. 

Plus side of TS is that it will check if you assign correct type to a variable, hint you about parameters of function etc.

Negative side; You need to compile the code before running it. 

There is more to both sides, but this is the basic gist.

**Comment by JuanIrache** [comment]
Probably not at the moment, Maybe at some point down the road

**Comment by Akxe** [comment]
@JuanIrache, I see you started using Typescript now. Would it be the time to move to Typescript? Or at least add a type definition?

**Comment by JuanIrache** [comment]
Hi. Since I maintain this and I don't work with TypeScript, I don't think it's a viable idea
